Rename folders
helsenorgelab/pasientdata pull request #25
Opened 2019-08-08 12:44 UTC by losolio

* Moved the WEB folder into src folder, and renamed it to citizenapp. 
* Renamed Spark folder to fhirserver, as a preparation to remove Spark source code and replace with nuget packages

2019-08-08 14:30 UTC, kennethmyhra requested changes
Oppdaterer du README/setup guiden så den har riktig path til webapplikasjonen

2019-08-08 14:32 UTC, kennethmyhra commented
Ser også ut som du har konflikter på loginpage.js og loginpage.css?

2019-08-08 14:36 UTC, tanu1208 commented
login.js og css er endra pga advarsel teksten, så dere må kanskje gjøre denne prosessen på nytt eller merge master inn i branch’n deres

2019-08-08 20:27 UTC, losolio commented
@kennethmyhra Takk, har oppdatert path til app og håndtert konflikter!

2019-08-12 06:33 UTC, kennethmyhra approved these changes

2019-08-12 06:33 UTC, merged